<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-15 at 13:23:51.
 */
class RolesTest extends CTestCase {

    /**
     * @var Roles
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Roles;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Roles::model
     * @todo   Implement testModel().
     */
    public function testModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Roles::getRolesUsers
     * @todo   Implement testGetRolesUsers().
     */
    public function testGetRolesUsers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Roles::getByPermissions
     * @todo   Implement testGetByPermissions().
     */
    public function testGetByPermissions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Roles::getUsers
     * @todo   Implement testGetUsers().
     */
    public function testGetUsers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Roles::create
     * @todo   Implement testCreate().
     * @dataProvider provider
     */
    public function testCreate($name, $description, $user_k) {
        // insert a comment in pending status
        $identity = new UserIdentity('test', 'admin');
        $identity->authenticate();
        $mockSession = $this->getMock('CHttpSession', array('regenerateID'));
        Yii::app()->setComponent('session', $mockSession);
        Yii::app()->user->login($identity);

        $roles = new Roles();

        $params = array("name" => $name, "description" => $description, "user_k" => $user_k);

        $mess = $roles->Create($params);

        if ($mess['success']) {

            // verify the comment is in pending status
            $roles1 = Roles::model()->findByPk($mess['id']);
            $this->assertTrue($roles1 instanceof Roles);

            $this->assertEquals($name, $roles1->name);
            $this->assertEquals($description, $roles1->description);
        } else {
            print_r($mess['message']);
        }
    }

    /**
     * @covers Roles::write
     * @todo   Implement testWrite().
     */
    public function testWrite() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    public function provider() {
        return array(
            array("Xavier", "sociis natoque penatibus", 9),
            array("Justin", "feugiat placerat velit.", 3),
            array("Howard", "arcu vel quam", 7),
            array("Zephania", "ac turpis egestas.", 5),
            array("Giacomo", "arcu. Vivamus sit", 5),
            array("Otto", "commodo ipsum. Suspendisse", 5),
            array("Curran", "tellus. Nunc lectus", 10),
            array("Finn", "commodo auctor velit.", 2),
            array("Murphy", "Ut semper pretium", 8),
            array("Wylie", "erat neque non", 9)
        );
    }

}
