<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-14 at 12:56:28.
 */
class WmsAreaTest extends PHPUnit_Framework_TestCase {

    /**
     * @var WmsArea
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WmsArea;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers WmsArea::model
     * @todo   Implement testModel().
     */
    public function testModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WmsArea::getLists
     * @todo   Implement testGetLists().
     */
    public function testGetLists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WmsArea::getComboSelect
     * @todo   Implement testGetComboSelect().
     */
    public function testGetComboSelect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WmsArea::Create
     * @todo   Implement testCreate().
     */
    public function testCreate($name, $area_code, $wh_id, $area_type_id, $active) {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WmsArea::Write
     * @todo   Implement testWrite().
     */
    public function testWrite($id, $name, $area_code, $wh_id, $area_type_id, $active) {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WmsArea::Deactive
     * @todo   Implement testDeactive().
     */
    public function testDeactive($id) {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    public function insertProvider() {
        return array(
            array('Area 1', 'W012', 11, 1),
            array('Area 2', 'W013', 12, 1),
            array('Area 3', 'W014', 11, 1),
            array('Area 4', 'W015', 12, 1),
            array('Area 5', '', 20, 1),
            array('Area', 'W015', 20, 1),
        );
    }

    public function updateProvider() {
        return array(
            array(1, 'Warehouse 1', 'W001', 11, 1), //OK
            array(2, 'Warehouse 2', 'W002', 12, 1),
            array(3, 'Warehouse 3', 'W003', 11, 1),
            array(4, 'Warehouse 4', 'W004', 12, 1),
            array(5, 'Warehouse 5', 'W005', 20, 1),
            array(6, '', 'W006', 11, 1),
            array(7, 'Warehouse 7', '', 12, 1),
            array(8, 'Warehouse 8', 'W008', 20, 0),
        );
    }

    public function deleteProvider() {
        return array(
            array(9, 'john'), //OK
            array(10, 'susan'), //OK
            array(11, 'test'), //OK
        );
    }
    