<?php

/**
 * This is the model base class for the table "roles".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Roles".
 *
 * Columns in table "roles" available as properties of the model,
 * followed by relations of table "roles" available as properties of the model.
 *
 * @property integer $role_k
 * @property string $name
 * @property string $description
 *
 * @property RolePermissions[] $rolePermissions
 * @property UserRoles[] $userRoles
 */
abstract class BaseRoles extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'roles';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Roles|Roles', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, description', 'required'),
			array('name', 'length', 'max'=>50),
			array('role_k, name, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'rolePermissions' => array(self::HAS_MANY, 'RolePermissions', 'role_k'),
			'userRoles' => array(self::HAS_MANY, 'UserRoles', 'role_k'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'role_k' => Yii::t('app', 'Role K'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'rolePermissions' => null,
			'userRoles' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('role_k', $this->role_k);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}