<?php

/**
 * This is the model base class for the table "conf_menutree".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ConfMenuTree".
 *
 * Columns in table "conf_menutree" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $text
 * @property string $view
 * @property string $module
 * @property string $iconCls
 * @property integer $parent_id
 * @property integer $sort
 * @property integer $active
 * @property integer $create_uid
 * @property string $create_date
 * @property integer $write_uid
 * @property string $write_date
 * @property integer $clickable
 *
 */
abstract class BaseConfMenuTree extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'conf_menutree';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ConfMenuTree|ConfMenuTrees', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, text, active, create_uid, create_date, write_uid, write_date, clickable', 'required'),
			array('parent_id, sort, active, create_uid, write_uid, clickable', 'numerical', 'integerOnly'=>true),
			array('view, module, iconCls', 'safe'),
			array('view, module, iconCls, parent_id, sort', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, text, view, module, iconCls, parent_id, sort, active, create_uid, create_date, write_uid, write_date, clickable', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'text' => Yii::t('app', 'Text'),
			'view' => Yii::t('app', 'View'),
			'module' => Yii::t('app', 'Module'),
			'iconCls' => Yii::t('app', 'Icon Cls'),
			'parent_id' => Yii::t('app', 'Parent'),
			'sort' => Yii::t('app', 'Sort'),
			'active' => Yii::t('app', 'Active'),
			'create_uid' => Yii::t('app', 'Create Uid'),
			'create_date' => Yii::t('app', 'Create Date'),
			'write_uid' => Yii::t('app', 'Write Uid'),
			'write_date' => Yii::t('app', 'Write Date'),
			'clickable' => Yii::t('app', 'Clickable'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('text', $this->text, true);
		$criteria->compare('view', $this->view, true);
		$criteria->compare('module', $this->module, true);
		$criteria->compare('iconCls', $this->iconCls, true);
		$criteria->compare('parent_id', $this->parent_id);
		$criteria->compare('sort', $this->sort);
		$criteria->compare('active', $this->active);
		$criteria->compare('create_uid', $this->create_uid);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('write_uid', $this->write_uid);
		$criteria->compare('write_date', $this->write_date, true);
		$criteria->compare('clickable', $this->clickable);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}